@startuml
participant "Website User"
participant "api-gateway"
participant "shop"
participant "warehouse"
participant "images"
participant "cognito"
database "db"
participant "image-cache.s3.eu-west-1.amazonaws.com"
"Website User" -> "api-gateway": GET 
activate "api-gateway"

"api-gateway" --> "Website User": 307 Temporary Redirect
deactivate "api-gateway"
"Website User" -> "cognito": GET oauth2/authorize
activate "cognito"

"cognito" --> "Website User": 302 Found
deactivate "cognito"
"Website User" -> "cognito": GET oauth2/login
activate "cognito"

"cognito" --> "Website User": 200 OK
deactivate "cognito"
"Website User" -> "cognito": POST oauth2/login
activate "cognito"

"cognito" --> "Website User": 303 See Other
deactivate "cognito"
"Website User" -> "api-gateway": GET oauth/callback
activate "api-gateway"
"api-gateway" -> "cognito": POST oauth2/token
activate "cognito"

"cognito" --> "api-gateway": 200 OK
deactivate "cognito"
"api-gateway" --> "Website User": 307 Temporary Redirect
deactivate "api-gateway"
"Website User" -> "api-gateway": GET 
activate "api-gateway"
"api-gateway" -> "shop": GET 
activate "shop"
"shop" -> "warehouse": GET v1/items
activate "warehouse"
"warehouse" <-> "db": items
"warehouse" --> "shop": 200 OK
deactivate "warehouse"
"shop" --> "api-gateway": 200 OK
deactivate "shop"
"api-gateway" --> "Website User": 200 OK
deactivate "api-gateway"
"Website User" -> "api-gateway": GET 
activate "api-gateway"
"api-gateway" -> "shop": GET 
activate "shop"
"shop" -> "warehouse": GET v1/items
activate "warehouse"
"warehouse" <-> "db": items
"warehouse" --> "shop": 200 OK
deactivate "warehouse"
"shop" --> "api-gateway": 200 OK
deactivate "shop"
"api-gateway" --> "Website User": 200 OK
deactivate "api-gateway"
"Website User" -> "api-gateway": GET img/{.+}
activate "api-gateway"
"api-gateway" -> "images": GET img/{id}
activate "images"
"images" -> "image-cache.s3.eu-west-1.amazonaws.com": GET {bucketKey:.+}
activate "image-cache.s3.eu-west-1.amazonaws.com"

"image-cache.s3.eu-west-1.amazonaws.com" --> "images": 500 Internal Server Error
deactivate "image-cache.s3.eu-west-1.amazonaws.com"
"images" --> "api-gateway": 503 Service Unavailable
deactivate "images"
"api-gateway" --> "Website User": 503 Service Unavailable
deactivate "api-gateway"
@enduml
