@startuml
    participant "Customer"
participant "api-gateway"
participant "shop"
participant "warehouse"
participant "images"
participant "cognito"
database "db"
participant "image-cache.s3.eu-west-1.amazonaws.com"
"Customer" -> "api-gateway": GET
activate "api-gateway"

"api-gateway" -[#DarkBlue]> "Customer": <color:DarkBlue> 307 Temporary Redirect
deactivate "api-gateway"
"Customer" -> "cognito": GET oauth2/authorize
activate "cognito"

"cognito" -[#DarkBlue]> "Customer": <color:DarkBlue> 302 Found
deactivate "cognito"
"Customer" -> "cognito": GET oauth2/login
activate "cognito"

"cognito" -[#DarkGreen]> "Customer": <color:DarkGreen> 200 OK
deactivate "cognito"
"Customer" -> "cognito": POST oauth2/login
activate "cognito"

"cognito" -[#DarkBlue]> "Customer": <color:DarkBlue> 303 See Other
deactivate "cognito"
"Customer" -> "api-gateway": GET oauth/callback
activate "api-gateway"
"api-gateway" -> "cognito": POST oauth2/token
activate "cognito"

"cognito" -[#DarkGreen]> "api-gateway": <color:DarkGreen> 200 OK
deactivate "cognito"
"api-gateway" -[#DarkBlue]> "Customer": <color:DarkBlue> 307 Temporary Redirect
deactivate "api-gateway"
"Customer" -> "api-gateway": GET
activate "api-gateway"
"api-gateway" -> "shop": GET
activate "shop"
"shop" -> "warehouse": GET v1/items
activate "warehouse"
"warehouse" <-> "db": items
"warehouse" -[#DarkGreen]> "shop": <color:DarkGreen> 200 OK
deactivate "warehouse"
"shop" -[#DarkGreen]> "api-gateway": <color:DarkGreen> 200 OK
deactivate "shop"
"api-gateway" -[#DarkGreen]> "Customer": <color:DarkGreen> 200 OK
deactivate "api-gateway"
"Customer" -> "api-gateway": GET
activate "api-gateway"
"api-gateway" -> "shop": GET
activate "shop"
"shop" -> "warehouse": GET v1/items
activate "warehouse"
"warehouse" <-> "db": items
"warehouse" -[#DarkGreen]> "shop": <color:DarkGreen> 200 OK
deactivate "warehouse"
"shop" -[#DarkGreen]> "api-gateway": <color:DarkGreen> 200 OK
deactivate "shop"
"api-gateway" -[#DarkGreen]> "Customer": <color:DarkGreen> 200 OK
deactivate "api-gateway"
"Customer" -> "api-gateway": GET img/{.+}
activate "api-gateway"
"api-gateway" -> "images": GET img/{id}
activate "images"
"images" -> "image-cache.s3.eu-west-1.amazonaws.com": GET {bucketKey:.+}
activate "image-cache.s3.eu-west-1.amazonaws.com"

"image-cache.s3.eu-west-1.amazonaws.com" X-[#FireBrick]> "images": <color:FireBrick> 500 Internal Server Error
deactivate "image-cache.s3.eu-west-1.amazonaws.com"
"images" X-[#FireBrick]> "api-gateway": <color:FireBrick> 503 Service Unavailable
deactivate "images"
"api-gateway" X-[#FireBrick]> "Customer": <color:FireBrick> 503 Service Unavailable
deactivate "api-gateway"
@enduml
