@startuml
title InMemoryClusterTest - can load stock list and order item

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System(customer, "Customer")
System(apigateway, "api-gateway")
System(shop, "shop")
System(warehouse, "warehouse")
System(images, "images")
System(cognito, "cognito")
ContainerDb(db, "db")
System(imagecaches3euwest1amazonawscom, "image-cache.s3.eu-west-1.amazonaws.com")
System(deptstore, "dept-store")
System(emaileuwest1amazonawscom, "email.eu-west-1.amazonaws.com")
System(eventstream, "event-stream")    
Rel_D(customer, apigateway, " ")
Rel_D(customer, cognito, " ")
Rel_D(apigateway, cognito, " ") 
Rel_D(apigateway, shop, " ")
Rel_D(shop, warehouse, " ")
Rel_D(warehouse, db, " ") 
Rel_D(apigateway, images, " ") 
Rel_D(images, imagecaches3euwest1amazonawscom, " ") 
Rel_D(warehouse, deptstore, " ") 
Rel_D(shop, emaileuwest1amazonawscom, " ")
Rel_D(shop, eventstream, " ")
@enduml
