@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System(customer, "Customer")
System(shop, "shop")
System(warehouse, "warehouse")    
Rel_D(customer, shop, " ")
Rel_D(shop, warehouse, " ")
@enduml
