@startuml
title ShopTest - can list items
participant "Customer"
participant "shop"
participant "warehouse"
"Customer" -> "shop": GET list
activate "shop"
"shop" -> "warehouse": GET v1/items
activate "warehouse"

"warehouse" --> "shop": 200 OK
deactivate "warehouse"
"shop" --> "Customer": 200 OK
deactivate "shop"
@enduml
