@startuml
title WarehouseApiTests - dispatch item

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System(client, "client")
System(warehouse, "warehouse")
ContainerDb(db, "db")
System(deptstore, "dept-store")    
Rel_D(client, warehouse, " ") 
Rel_D(warehouse, db, " ") 
Rel_D(warehouse, deptstore, " ")     
@enduml