@startuml
title UniverseTests - views item, orders, receives confirmation
participant "Customer"
participant "api-gateway"
participant "shop"
participant "warehouse"
participant "images"
database "db"
participant "image-cache.s3.eu-west-1.amazonaws.com"
participant "dept-store"
participant "email.eu-west-1.amazonaws.com"
queue "event-stream"
"Customer" -> "api-gateway": GET list
activate "api-gateway"
"api-gateway" -> "shop": GET list
activate "shop"
"shop" -> "warehouse": GET v1/items
activate "warehouse"
"warehouse" <-> "db": items
"warehouse" -[#DarkGreen]> "shop": <color:DarkGreen> 200 OK
deactivate "warehouse"
"shop" -[#DarkGreen]> "api-gateway": <color:DarkGreen> 200 OK
deactivate "shop"
"api-gateway" -[#DarkGreen]> "Customer": <color:DarkGreen> 200 OK
deactivate "api-gateway"
"Customer" -> "api-gateway": GET img/{.+}
activate "api-gateway"
"api-gateway" -> "images": GET img/{id}
activate "images"
"images" -> "image-cache.s3.eu-west-1.amazonaws.com": GET {bucketKey:.+}
activate "image-cache.s3.eu-west-1.amazonaws.com"

"image-cache.s3.eu-west-1.amazonaws.com" -[#DarkGreen]> "images": <color:DarkGreen> 200 OK
deactivate "image-cache.s3.eu-west-1.amazonaws.com"
"images" -[#DarkGreen]> "api-gateway": <color:DarkGreen> 200 OK
deactivate "images"
"api-gateway" -[#DarkGreen]> "Customer": <color:DarkGreen> 200 OK
deactivate "api-gateway"
"Customer" -> "api-gateway": POST order/{id}
activate "api-gateway"
"api-gateway" -> "shop": POST order/{id}
activate "shop"
"shop" -> "warehouse": POST v1/dispatch
activate "warehouse"
"warehouse" <-> "db": items
"warehouse" <-> "db": adjust
"warehouse" -> "dept-store": POST v1/order
activate "dept-store"

"dept-store" -[#DarkGreen]> "warehouse": <color:DarkGreen> 200 OK
deactivate "dept-store"
"warehouse" -[#DarkGreen]> "shop": <color:DarkGreen> 202 Accepted
deactivate "warehouse"
"shop" -> "email.eu-west-1.amazonaws.com": POST v2/email/outbound-emails
activate "email.eu-west-1.amazonaws.com"

"email.eu-west-1.amazonaws.com" -[#DarkGreen]> "shop": <color:DarkGreen> 200 OK
deactivate "email.eu-west-1.amazonaws.com"
"shop" -> "event-stream": CustomerOrder(item=1)
"shop" -[#DarkGreen]> "api-gateway": <color:DarkGreen> 200 OK
deactivate "shop"
"api-gateway" -[#DarkGreen]> "Customer": <color:DarkGreen> 200 OK
deactivate "api-gateway"
@enduml