on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew -i check
