on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/cache@v3.2.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew -i check
